@startuml
'https://plantuml.com/activity-diagram-beta

start
:output_header(main_header);
:new name request;
if (new name) then (string)
  if (try create_database(new name)) then (FileExistsError)
    :output_string(File already exists);
    if (overwrite database request) then (yes)
      :delete_database(new name);
      :create_database(new name);
    else (no)
      :output_string(keep existing database);
      :return False;
      stop
    endif
  else (no exception)
  endif
  :menu_items = MAIN_MENU;
  :output_string(current database name);
  :return True;
else (None)
  :return False;
  stop
endif
stop

@enduml
