@startuml
'https://plantuml.com/activity-diagram-beta

start
:output_header(main_header);
if (bookmark name request) then (None or invalid chars)
  :return False;
  stop
else (string)
  if (is name 'roots'?) then (yes)
    :output_string(folder roots can not be deleted);
    :return False;
    stop
  else (no)
  endif
  if (try model.delete_node) then (NodeNotExists, FolderNotEmpty)
    :output_string(folder does not exist),
                                 or
    output_string(folder does not empty;
    :return False;
    stop
  else (no exception)
    :output_string(success);
    :return True;
    stop
  endif
endif
@enduml
